/*
 * generated by Xtext 2.10.0
 */
package it.csec.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class VsdlStandaloneSetup extends VsdlStandaloneSetupGenerated {

	def static void doSetup() {
		new VsdlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
