/*
 * generated by Xtext 2.11.0
 */
package it.csec.xtext.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class VsdlWebModule extends AbstractVsdlWebModule {
}
