/*
 * generated by Xtext 2.11.0.RC2
 */
package it.csec.xtext.ide

import com.google.inject.Guice
import it.csec.xtext.VsdlRuntimeModule
import it.csec.xtext.VsdlStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class VsdlIdeSetup extends VsdlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new VsdlRuntimeModule, new VsdlIdeModule))
	}
	
}
